import { AirplaneTiltIcon, ApertureIcon, BabyIcon, BarbellIcon, BookOpenIcon, BriefcaseIcon, CameraIcon, CarIcon, ChefHatIcon, CouchIcon, CpuIcon, FilmStripIcon, FlaskIcon, ForkKnifeIcon, GameControllerIcon, GraduationCapIcon, HammerIcon, HandHeartIcon, HeadphonesIcon, HeartbeatIcon, MicrophoneStageIcon, MusicNotesIcon, NewspaperIcon, PaletteIcon, PawPrintIcon, PersonSimpleTaiChiIcon, PiggyBankIcon, SmileyWinkIcon, SparkleIcon, StickerIcon, TShirtIcon, TargetIcon, TelevisionIcon, TentIcon, TranslateIcon, VolleyballIcon } from '@phosphor-icons/react/ssr';
import type { Icon as PhosphorIcon } from '@phosphor-icons/react';
import type { InterestId } from '@clipers/db';

export const INTEREST_ICONS: Record<InterestId, PhosphorIcon> = {
  music: MusicNotesIcon,
  kpop: MicrophoneStageIcon,
  dance: PersonSimpleTaiChiIcon,
  entertainment: TelevisionIcon,
  comedy: SmileyWinkIcon,
  film_drama: FilmStripIcon,
  animation_webtoon: StickerIcon,
  gaming: GameControllerIcon,
  asmr: HeadphonesIcon,
  vlog: CameraIcon,
  beauty: SparkleIcon,
  fashion: TShirtIcon,
  food: ForkKnifeIcon,
  cooking: ChefHatIcon,
  travel: AirplaneTiltIcon,
  pets: PawPrintIcon,
  kids_family: BabyIcon,
  home_interior: CouchIcon,
  outdoor: TentIcon,
  sports: VolleyballIcon,
  fitness: BarbellIcon,
  health: HeartbeatIcon,
  education: GraduationCapIcon,
  language: TranslateIcon,
  science: FlaskIcon,
  tech: CpuIcon,
  finance: PiggyBankIcon,
  business: BriefcaseIcon,
  news: NewspaperIcon,
  books: BookOpenIcon,
  self_improvement: TargetIcon,
  social_impact: HandHeartIcon,
  art_design: PaletteIcon,
  photo_video: ApertureIcon,
  diy: HammerIcon,
  autos: CarIcon,
};
