import {
  Aperture,
  Baby,
  BookImage,
  BookOpen,
  Briefcase,
  Camera,
  Car,
  ChefHat,
  Cpu,
  Dumbbell,
  Film,
  FlaskConical,
  Gamepad2,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  HeartPulse,
  Languages,
  Laugh,
  MicVocal,
  Music,
  Newspaper,
  Palette,
  PawPrint,
  PersonStanding,
  PiggyBank,
  Plane,
  Shirt,
  Sofa,
  Sparkles,
  Target,
  Tent,
  Tv,
  Utensils,
  Volleyball,
  type LucideIcon,
} from 'lucide-react';
import type { InterestId } from '@clipers/db';

export const INTEREST_ICONS: Record<InterestId, LucideIcon> = {
  music: Music,
  kpop: MicVocal,
  dance: PersonStanding,
  entertainment: Tv,
  comedy: Laugh,
  film_drama: Film,
  animation_webtoon: BookImage,
  gaming: Gamepad2,
  asmr: Headphones,
  vlog: Camera,
  beauty: Sparkles,
  fashion: Shirt,
  food: Utensils,
  cooking: ChefHat,
  travel: Plane,
  pets: PawPrint,
  kids_family: Baby,
  home_interior: Sofa,
  outdoor: Tent,
  sports: Volleyball,
  fitness: Dumbbell,
  health: HeartPulse,
  education: GraduationCap,
  language: Languages,
  science: FlaskConical,
  tech: Cpu,
  finance: PiggyBank,
  business: Briefcase,
  news: Newspaper,
  books: BookOpen,
  self_improvement: Target,
  social_impact: HandHeart,
  art_design: Palette,
  photo_video: Aperture,
  diy: Hammer,
  autos: Car,
};
